### ISSUE TITLE
Not able to restore data from local storage and google drive

### ISSUE THREAD

**Issue by arulrajnet** [perfectrium/spendria#2] opened 2020-10-04 15:56 UTC
Its just shows blank screen in File and Google drive

![WhatsApp Image 2020-10-04 at 9 23 26 PM](https://user-images.githubusercontent.com/834529/95020342-2f129d00-0688-11eb-8fa9-86c44d5e4c7e.jpeg)

**Comment by perfectrium** [comment] 2020-10-08 20:16
Duplicate of #1

**Closed as completed by perfectrium** 2020-10-08 20:16 UTC
